esgi_user:
    resource: "@ESGIUserBundle/Resources/config/routing.yml"
    prefix:   /

esgi_blog_yml:
    resource: "@ESGIBlogBundle/Resources/config/routing.yml"
    prefix:   /

esgi_blog:
    resource: "@ESGIBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

propose:
    pattern:  /propose
    defaults: { _controller: @ESGIBlogBundle:ProposeController:proposeAction }


register:
    pattern:  /register
    defaults: { _controller: @ESGIUserBundle:DefaultController:indexAction }



admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
