esgi_blog_yml:
    resource: "@ESGIBlogBundle/Resources/config/routing.yml"
    prefix:   /

esgi_blog:
    resource: "@ESGIBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
