services:
    sonata.admin.post:
        class: ESGI\BlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - ESGI\BlogBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [ESGIBlogBundle]]
    sonata.admin.category:
        class: ESGI\BlogBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - ESGI\BlogBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [ESGIBlogBundle]]
    sonata.admin.comment:
        class: ESGI\BlogBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comment" }
        arguments:
            - ~
            - ESGI\BlogBundle\Entity\Comment
            - ~
        calls:
            - [ setTranslationDomain, [ESGIBlogBundle]]
    sonata.admin.user:
        class: ESGI\BlogBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - ESGI\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [ESGIBlogBundle]]
